apiVersion: pfe.rhpds.com/v1
kind: Gitea
metadata:
  name: gitea
  namespace: gdfkube
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  giteaImageTag: "1.22"
  giteaVolumeSize: 4Gi
  giteaSsl: true
  postgresqlVolumeSize: 4Gi
  giteaAdminUser: gdfkube-admin
  giteaAdminPassword: admin
  giteaAdminEmail: admin@gdfkube.local
  giteaDisableRegistration: true
