apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init
  namespace: gdfkube
  annotations:
    argocd.argoproj.io/sync-wave: "12"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-init
          image: docker.io/apache/kafka:3.7.2
          command: ["bash", "/scripts/init-topics.sh"]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: kafka-init-scripts
            defaultMode: 0755
