apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gdfkube
resources:
  - rbac.yaml
  - configmaps.yaml
  - base-domain-discovery-job.yaml
  - mongo-init-job.yaml
  - mongo-seed-job.yaml
  - mongo-collections-init-job.yaml
  - kafka-init-job.yaml
  - connect-topics-init-job.yaml
  - gitea-bootstrap-job.yaml
  - gitea-seed-job.yaml
  - gitea-token-sync-job.yaml
  - debezium-init-job.yaml
  - sonar-bootstrap-job.yaml
