apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init
  namespace: gdfkube
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-options: Replace=true
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mongo-init
          image: mongo:7.0
          command: ["mongosh", "--host", "mongo1:27017", "/scripts/init-rs.js"]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: mongo-init-scripts
