apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin
  namespace: gdfkube
type: Opaque
stringData:
  username: gdfkube-admin
  password: admin # trufflehog:ignore
  email: admin@gdfkube.local
---
apiVersion: v1
kind: Secret
metadata:
  name: sonar-db
  namespace: gdfkube
type: Opaque
stringData:
  username: sonar
  password: sonar # trufflehog:ignore
  database: sonar
---
apiVersion: v1
kind: Secret
metadata:
  name: sonar-admin
  namespace: gdfkube
type: Opaque
stringData:
  password: "GdfKube-S0nar!" # trufflehog:ignore
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-pat
  namespace: gdfkube
type: Opaque
stringData:
  token: "" # trufflehog:ignore
---
apiVersion: v1
kind: Secret
metadata:
  name: sonar-token
  namespace: gdfkube
type: Opaque
stringData:
  token: "" # trufflehog:ignore
