FROM registry.access.redhat.com/ubi9/openjdk-21:1.21 AS build

USER root
RUN microdnf install -y unzip && microdnf clean all
WORKDIR /build

COPY .mvn/ .mvn/
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline -B

COPY src/ src/
RUN ./mvnw package -DskipTests -B

FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.21

USER root

ARG HELM_VERSION=v3.16.3
ARG HELM_SHA256=f5355c79190951eed23c5432a3b920e071f4c00a64f75e077de0dd4cb7b294ea
RUN microdnf install -y gzip tar \
 && microdnf clean all \
 && curl -fsSL -o /tmp/helm.tgz "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz" \
 && echo "${HELM_SHA256}  /tmp/helm.tgz" | sha256sum -c - \
 && tar -xzf /tmp/helm.tgz -C /tmp \
 && mv /tmp/linux-amd64/helm /usr/local/bin/helm \
 && rm -rf /tmp/helm.tgz /tmp/linux-amd64

USER 185

COPY --from=build --chown=185 /build/build/quarkus-app/lib/ /deployments/lib/
COPY --from=build --chown=185 /build/build/quarkus-app/*.jar /deployments/
COPY --from=build --chown=185 /build/build/quarkus-app/app/ /deployments/app/
COPY --from=build --chown=185 /build/build/quarkus-app/quarkus/ /deployments/quarkus/
EXPOSE 8080

ENV JAVA_OPTS_APPEND="-Xmx512m"
ENV LANG=en_US.UTF-8

ENTRYPOINT ["java", "-jar", "/deployments/quarkus-run.jar"]
