apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gdfkube-platform
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/HugoPfeffer/gdfkube.git
    targetRevision: main-openshift
    path: gdfkube-src/gdfkube-infra/platform/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
