source:
  repoURL: https://github.com/HugoPfeffer/gdfkube.git
  targetRevision: worktree-openshift-argocd-bootstrap-plan

deployer:
  domain: ""

argocd:
  namespace: openshift-gitops
  project: default
  destination:
    server: https://kubernetes.default.svc

workload:
  namespace: gdfkube
