apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gdfkube-org-discovery
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  project: {{ .Values.argocd.project }}
  source:
    {{- include "gdfkube-platform.source" . | nindent 4 }}
    path: gdfkube-src/gdfkube-infra/platform/manifests/org-discovery
  destination:
    server: {{ .Values.argocd.destination.server }}
    namespace: {{ .Values.argocd.namespace }}
  syncPolicy:
    {{- include "gdfkube-platform.syncPolicy" . | nindent 4 }}
