apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gdfkube-secrets
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: {{ .Values.argocd.project }}
  source:
    {{- include "gdfkube-platform.source" . | nindent 4 }}
    path: gdfkube-src/gdfkube-infra/platform/manifests/secrets
  destination:
    {{- include "gdfkube-platform.destination" . | nindent 4 }}
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: gitea-pat
      jsonPointers:
        - /data/token
        - /stringData
    - group: ""
      kind: Secret
      name: sonar-token
      jsonPointers:
        - /data/token
        - /stringData
  syncPolicy:
    {{- include "gdfkube-platform.syncPolicy" . | nindent 4 }}
    syncOptions:
      - RespectIgnoreDifferences=true
