apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gdfkube-builds
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: {{ .Values.argocd.project }}
  source:
    {{- include "gdfkube-platform.source" . | nindent 4 }}
    path: gdfkube-src/gdfkube-infra/platform/manifests/builds
  destination:
    {{- include "gdfkube-platform.destination" . | nindent 4 }}
  ignoreDifferences:
    - group: build.openshift.io
      kind: BuildConfig
      jqPathExpressions:
        - .status
        - .spec.triggers
  syncPolicy:
    {{- include "gdfkube-platform.syncPolicy" . | nindent 4 }}
    syncOptions:
      - RespectIgnoreDifferences=true
