apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gdfkube-data-sonar
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: {{ .Values.argocd.project }}
  source:
    {{- include "gdfkube-platform.source" . | nindent 4 }}
    path: gdfkube-src/gdfkube-infra/platform/manifests/sonar
  destination:
    {{- include "gdfkube-platform.destination" . | nindent 4 }}
  syncPolicy:
    {{- include "gdfkube-platform.syncPolicy" . | nindent 4 }}
