apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gdfkube-apps
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: {{ .Values.argocd.project }}
  source:
    {{- include "gdfkube-platform.source" . | nindent 4 }}
    path: gdfkube-src/gdfkube-infra/platform/manifests/apps
  destination:
    {{- include "gdfkube-platform.destination" . | nindent 4 }}
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.spec.containers[].image
        - .spec.template.spec.initContainers[]?.image
  syncPolicy:
    {{- include "gdfkube-platform.syncPolicy" . | nindent 4 }}
    syncOptions:
      - RespectIgnoreDifferences=true
