apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: {{ .Values.system.naming.hostedClusterName }}-workers
  namespace: {{ .Values.system.naming.namespace }}
  labels:
    {{- toYaml .Values.system.labels | nindent 4 }}
spec:
  replicas: {{ .Values.vars.replicas | default 1 }}
