apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: gdfkube-gitops
  namespace: gdfkube-gitops
spec:
  sourceNamespaces:
    - gdfkube-gitops
  defaultClusterScopedRoleDisabled: false
  controller: {}
  repo: {}
  applicationSet: {}
  server:
    route:
      enabled: true
  redis: {}
  sso: null
