apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gdfkube-infra-orgs
  namespace: gdfkube-gitops
spec:
  generators:
    - git:
        repoURL: http://gitea.gdfkube.svc:3000/gdfkube/gdfkube-orgs.git
        revision: HEAD
        directories:
          - path: orgs/*
  template:
    metadata:
      name: 'gdfkube-infra-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: http://gitea.gdfkube.svc:3000/gdfkube/gdfkube-orgs.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: gdfkube-gitops
      syncPolicy: {}
