apiVersion: v1
kind: Secret
metadata:
  name: gitea-orgs-repo-creds
  namespace: gdfkube-gitops
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  url: https://gitea-gitea.apps.gdfkube.gov/gdfkube
