apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: hc-pullsecret-distributor
  namespace: {{ .Values.system.naming.policyNamespace }}
  labels:
    {{- toYaml .Values.system.labels | nindent 4 }}
spec:
  remediationAction: enforce
  severity: medium
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Secret
        type: kubernetes.io/dockerconfigjson
        metadata:
          name: pull-secret
          namespace: '{{ "{{" }} (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "").metadata.name {{ "}}" }}'
        data:
          .dockerconfigjson: '{{ "{{" }} fromSecret "open-cluster-management" "kubevirt-secret" "pullSecret" {{ "}}" }}'
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: Secret
        type: Opaque
        metadata:
          name: sshkey
          namespace: '{{ "{{" }} (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "").metadata.name {{ "}}" }}'
        data:
          id_rsa.pub: '{{ "{{" }} fromSecret "open-cluster-management" "kubevirt-secret" "ssh-publickey" {{ "}}" }}'
