apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: {{ .Values.system.naming.clusterSet }}
  namespace: {{ .Values.system.naming.appProject }}
  labels:
    {{- toYaml .Values.system.labels | nindent 4 }}
spec:
  clusterSet: {{ .Values.system.naming.clusterSet }}
