quarkus.http.port=8080
quarkus.application.name=gdfkube-camel

camel.component.kafka.brokers=${KAFKA_BOOTSTRAP_SERVERS:kafka1:19092,kafka2:19092,kafka3:19092}

quarkus.mongodb.connection-string=${MONGODB_URI:mongodb://mongo1:27017,mongo2:27017,mongo3:27017/gdfkube?replicaSet=rs0}
quarkus.mongodb.database=gdfkube

app.git.provider=${APP_GIT_PROVIDER:gitea}
%dev.app.git.provider=mock
%prod.app.git.provider=gitea

app.system.base-domain=${APP_SYSTEM_BASE_DOMAIN:apps.gdfkube.gov}
app.system.release-image=${APP_SYSTEM_RELEASE_IMAGE:quay.io/openshift-release-dev/ocp-release:4.16.7-x86_64}
app.system.gitea-external-url=${APP_SYSTEM_GITEA_EXTERNAL_URL:https://gitea-gitea.apps.gdfkube.gov}
app.system.gitea-owner=${APP_SYSTEM_GITEA_OWNER:gdfkube}
